name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not installed"

      - name: Build Docker image
        run: |
          docker build -t taxfix-app .

      - name: Run Docker container
        run: |
          docker run -d --name taxfix-container -p 8000:8000 taxfix-app

      - name: Debug Model Path Inside Container
        run: |
          docker exec taxfix-container ls -R /app/src/model/models || echo "Model directory not found inside container"

      - name: Debug Running Container
        run: |
          docker ps -a
          docker logs taxfix-container

      - name: Test FastAPI endpoint
        run: |
          sleep 30
          docker exec taxfix-container curl -X POST "http://127.0.0.1:8000/predict" \
          -H "Content-Type: application/json" \
          -d @/app/src/test_input.json

      - name: Show FastAPI Logs
        run: docker logs taxfix-container || echo "No logs found"

      - name: Upload FastAPI Logs
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-logs
          path: app.log

      - name: Cleanup Docker
        run: |
          docker stop taxfix-container
          docker rm taxfix-container
