name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   docker:
    #     image: docker:19.03.12
    #     options: --privileged
    #     ports:
    #       - 8000:8000

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install --no-root
          poetry run make install

      # - name: Lint with flake8
      #   run: |
      #     poetry run flake8 .

      # - name: Run tests
      #   run: |
      #     poetry run pytest

      # - name: Build Docker image
      #   run: |
      #     docker build -t taxfix-app .

      # - name: Run Docker container
      #   run: |
      #     docker run -d -p 8000:8000 taxfix-app

      - name: Wait for FastAPI to start
        run: |
          for i in {1..3}; do
            if curl -s http://127.0.0.1:8000/health | grep "API is running"; then
              echo "FastAPI is up!"
              break
            fi
            echo "Waiting for FastAPI..."
            sleep 30
          done

      - name: Test FastAPI endpoint
        run: |
          curl -X POST "http://127.0.0.1:8000/predict" -H "Content-Type: application/json" -d @src/test_input.json